name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  REG: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to ACR using admin creds (no az cli needed)
      - name: Docker login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build & push the frontend image (traceable tag + latest)
      - name: Build and Push Frontend Image
        run: |
          docker build \
            -t "$REG/frontend:${{ env.IMAGE_TAG }}" \
            -t "$REG/frontend:latest" \
            ./frontend
          docker push "$REG/frontend:${{ env.IMAGE_TAG }}"
          docker push "$REG/frontend:latest"

      - name: Docker logout
        if: always()
        run: docker logout "$REG"
